services:
  single-image-nmj-analysis:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - MPLBACKEND=Agg
    command: streamlit run BTX.py --server.port=8501 --server.address=0.0.0.0 --server.fileWatcherType=none --server.runOnSave=false --browser.gatherUsageStats=false

  multiple-image-nmj-analysis:
    build: .
    volumes:
      - .:/app
    ports:
      - "8502:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - MPLBACKEND=Agg
    command: streamlit run BTX_batch.py --server.port=8501 --server.address=0.0.0.0 --server.fileWatcherType=none --server.runOnSave=false --browser.gatherUsageStats=false
